### PR TITLE
Create guide for beginners

### PR DESCRIPTION
**Pull request by lorencerri**
https://quick-db-guide.vercel.app

### CODE REVIEW

**Comment by lorencerri** [comment]
Please don't merge yet

**Comment by lorencerri** [comment]
TODO:
- Finish API Docs (possibly link autogen one)
- Make some more things interactive

**Comment by ShadowGaming100** [comment]
You should fix the web size

**Comment by lorencerri** [comment]
See https://github.com/plexidev/quick.db-guide

**Pull request closed without merging**
