### PR TITLE
Change class properties order depending on length

### PR DESCRIPTION
**Pull request by aidakhome**
Hello, 
I have changed the code style to give it a more modern look (single quotes, and no semicolons nor trailing commas).
Personally, I think that this change is better for the code because it looks more beautiful.

I also have changed the examples and I have ordered some class properties depending on length, from shortest to longest.

### CODE REVIEW

**Comment by Zelak312** [comment]
Hey thank you for this PR!
First and foremost I would love to have a discussion on this more "modern look" with you.

For me most of the changes for the look doesn't really make sense.
1) single quotes
   I usually always use double quote since when writing strings single quotes can come up more often than double quotes. Making it useful to use double quotes to not always escape the single quote if there is one. It is also something I like from other languages as some of them there is a difference between a string and a char. Keeping it the same here for me is just a plus even thought it doesn't affect anything. (Prettier should also auto fix single quotes to double quotes)

2) semicolons
   Semicolons normally doesn't do anything in JavaScript now-days but it can happen (in a very rare case) that a piece of JavaScript break because a semicolon wasn't used. (Prettier should also auto add semicolons for you when fixing it, so not that much of a pain to do manually)

3) trailling commas
   This I think is a plus when editing or going back to an array. the commas is already there to accept an other item whenever. removing it doesn't make much sense to me. (Prettier should also auto fix it and place them for you if you don't)
   
For the ordering of the class properties depending on length, I have nothing to say about this and it is totally welcome.

I would love to hear what you have two say about those 3 points I made for the "modern look". I am open to anything!

**Comment by aidakhome** [comment]
Hey! Good morning.

About what you said, I think that the single quote is better because it gives a more minimal look to the strings and makes it less intrusive? At least for me, double quotes give me a sense of strange.
Also, I think that Prettier can put double quotes if there's a single quote inside of a string.

About semicolons, I agree with you that in some parts of a JavaScript code it can break (eg. a for expression) but this is fixed by Prettier. I think that the removal of ONLY unnecessary semicolons gives the code a cleaner look.

In the part of trailing commas, I agree completely with you and I’m committing later to put them back.

Thank you for your time :)

**Comment by Zelak312** [comment]
Good morning,

I agree with both things you said but I want  the code be consistent. If it uses single quotes, use it everywhere and nothing else. Same for semicolons. If there is one use it everywhere also. Making it consistent is the key to having a good codebase.

I do know Prettier can fix those. I brought prettier up in this because it can actually do these little changes for us. My point was to show that it wasn't necessary to go out of our way to manually look for these semicolons to be added.

For me that it looks good or not is the last criteria on the list. The only point you brought up is "it looks better" but things looking better is subjective to each individual, there is no real reasons to change it here or at least that we discussed. That is why I will keep the double quotes. For the semicolons, same thing, if I use semicolons, I want it to be consistent so it should go everywhere. So adding semicolons only when needed is not ideal for me.

I am searching for more lf a partical reason to change theses instead of just the looks.

Feel free to debate those ideas also!

**Comment by aidakhome** [comment]
I agree with those points. 
May I put double quotes and semicolons back, changing only the property order so?

**Comment by Zelak312** [comment]
Yes, everything else is totally fine to me, I will be merging it a bit later.

Thank you for understanding and for the work you put in. It is always welcome and appreciated

**Comment by aidakhome** [comment]
You can merge the pull request.
Thank you for your time and for your points :)

**Comment by Zelak312** [comment]
Yes, I will merge now. I was doing something else which is why it took time

**Pull request merged**
